services:
  # PostgreSQL Database (only service running in Docker for development)
  # Frontend and Backend will run locally on the development machine
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medical_records
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medical-records

volumes:
  postgres_data:

networks:
  medical-records:
    driver: bridge
